name: 生成图片
on:
  push:
    tags:
      - 'v*'
jobs:
  genimg:
    name: 生成图片
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Check out zbp into repo
        run: git clone --depth=1 https://github.com/FloatTech/ZeroBot-Plugin.git repo

      - name: Generate images
        env:
          NOVELAI_API_KEY: ${{ secrets.NOVELAI_API_KEY }}
        run: go run main.go ./repo/plugin/ plugins

      - name: Remove zbp repo
        run: rm -rf repo

      - name: Commit back
        continue-on-error: true
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "生成图片"
          git push

      - name: Upload artifact
        uses: actions/upload-artifact@master
        if: ${{ !github.head_ref }}
        with:
          name: images
          path: plugins/
